# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField(blank=True, default=54000)),
                ('job_interest', models.CharField(choices=[(b'AN', b'Analyst'), (b'SW', b'Software'), (b'MA', b'Manager'), (b'AS', b'Assistant')], default=b'Software', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
    ]
