# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_keycredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default=b'hassamhassan.qc@gmail.com', max_length=100),
        ),
    ]
